version: '3.8'

services:
  web:
    build:
      context: . 
      dockerfile: docker/Dockerfile 
    container_name: ticketbuy_web
    ports:
      - "8080:80" 
    volumes:
      - ./src:/var/www/html
    restart: always
    network_mode: bridge 